name = "catppuccin-frappe"

[colors]
background = "#303446"
foreground = "#c6d0f5"
selection_bg = "#51576d"
selection_fg = "#c6d0f5"
overlay_bg = "#292c3a"
status_bg = "#232634"
status_fg = "#a5adce"
border = "#626880"
window_focus_border = "#e5c890"
search_match = { fg = "#303446", bg = "#e5c890" }
dim = "#737994"

[levels]
trace = "#737994"
debug = "#8caaee"
info = "#a6d189"
warn = "#e5c890"
error = "#e78284"
fatal = "#ca9ee6"
unknown = "#c6d0f5"

[ui]
timestamp = "#8caaee"
key = "#99d1db"
string = "#a6d189"
number = "#ef9f76"
bool = "#ca9ee6"
null = "#737994"
border_color = { fg = "#626880", bg = "#303446" }
border_width = 1
border_padding = 1
