name = "duskfox"

[colors]
background = "#232136"
foreground = "#e0def4"
selection_bg = "#433c59"
selection_fg = "#e0def4"
overlay_bg = "#2d2a45"
status_bg = "#191726"
status_fg = "#b6bac0"
border = "#3b3653"
window_focus_border = "#f6c177"
search_match = { fg = "#232136", bg = "#f6c177" }
dim = "#6e6a86"

[levels]
trace = "#6e6a86"
debug = "#569fba"
info = "#a3be8c"
warn = "#f6c177"
error = "#eb6f92"
fatal = "#c4a7e7"
unknown = "#e0def4"

[ui]
timestamp = "#9ccfd8"
key = "#569fba"
string = "#a3be8c"
number = "#ea9a97"
bool = "#c4a7e7"
null = "#6e6a86"
border_color = { fg = "#3b3653", bg = "#232136" }
border_width = 1
border_padding = 1
