name = "flexoki-dark"

[colors]
background = "#100f0f"
foreground = "#cecdc3"
selection_bg = "#343331"
selection_fg = "#cecdc3"
overlay_bg = "#1c1b1a"
status_bg = "#1c1b1a"
status_fg = "#b7b5ac"
border = "#403e3c"
window_focus_border = "#d0a215"
search_match = { fg = "#100f0f", bg = "#d0a215" }
dim = "#6f6e69"

[levels]
trace = "#6f6e69"
debug = "#4385be"
info = "#879a39"
warn = "#d0a215"
error = "#d14d41"
fatal = "#8b7ec8"
unknown = "#cecdc3"

[ui]
timestamp = "#4385be"
key = "#3aa99f"
string = "#879a39"
number = "#da702c"
bool = "#8b7ec8"
null = "#6f6e69"
border_color = { fg = "#403e3c", bg = "#100f0f" }
border_width = 1
border_padding = 1
