name = "flexoki-light"

[colors]
background = "#fffcf0"
foreground = "#100f0f"
selection_bg = "#dad8ce"
selection_fg = "#100f0f"
overlay_bg = "#f2f0e5"
status_bg = "#e6e4d9"
status_fg = "#6f6e69"
border = "#cecdc3"
window_focus_border = "#ad8301"
search_match = { fg = "#fffcf0", bg = "#ad8301" }
dim = "#878580"

[levels]
trace = "#878580"
debug = "#205ea6"
info = "#66800b"
warn = "#ad8301"
error = "#af3029"
fatal = "#5e409d"
unknown = "#100f0f"

[ui]
timestamp = "#205ea6"
key = "#24837b"
string = "#66800b"
number = "#bc5215"
bool = "#5e409d"
null = "#878580"
border_color = { fg = "#cecdc3", bg = "#fffcf0" }
border_width = 1
border_padding = 1
