name = "moonfly"

[colors]
background = "#080808"
foreground = "#c6c6c6"
selection_bg = "#323437"
selection_fg = "#e4e4e4"
overlay_bg = "#1c1c1c"
status_bg = "#1c1c1c"
status_fg = "#b2b2b2"
border = "#373c40"
window_focus_border = "#80a0ff"
search_match = { fg = "#080808", bg = "#80a0ff" }
dim = "#949494"

[levels]
trace = "#949494"
debug = "#79dac8"
info = "#8cc85f"
warn = "#e3c78a"
error = "#ff5454"
fatal = "#cf87e8"
unknown = "#c6c6c6"

[ui]
timestamp = "#79dac8"
key = "#80a0ff"
string = "#8cc85f"
number = "#de935f"
bool = "#cf87e8"
null = "#949494"
border_color = { fg = "#373c40", bg = "#080808" }
border_width = 1
border_padding = 1
