name = "nightfly"

[colors]
background = "#011627"
foreground = "#c3ccdc"
selection_bg = "#1d3b53"
selection_fg = "#c3ccdc"
overlay_bg = "#01111d"
status_bg = "#01111d"
status_fg = "#a1aab8"
border = "#2c3043"
window_focus_border = "#82aaff"
search_match = { fg = "#011627", bg = "#82aaff" }
dim = "#7c8f8f"

[levels]
trace = "#7c8f8f"
debug = "#7fdbca"
info = "#a1cd5e"
warn = "#e3d18a"
error = "#fc514e"
fatal = "#c792ea"
unknown = "#c3ccdc"

[ui]
timestamp = "#7fdbca"
key = "#82aaff"
string = "#a1cd5e"
number = "#f78c6c"
bool = "#c792ea"
null = "#7c8f8f"
border_color = { fg = "#2c3043", bg = "#011627" }
border_width = 1
border_padding = 1
