name = "poimandres"

[colors]
background = "#1b1e28"
foreground = "#a6accd"
selection_bg = "#303340"
selection_fg = "#e4f0fb"
overlay_bg = "#252b37"
status_bg = "#171922"
status_fg = "#a6accd"
border = "#3b4261"
window_focus_border = "#5de4c7"
search_match = { fg = "#1b1e28", bg = "#5de4c7" }
dim = "#506477"

[levels]
trace = "#506477"
debug = "#89ddff"
info = "#5de4c7"
warn = "#fffac2"
error = "#d0679d"
fatal = "#f087bd"
unknown = "#a6accd"

[ui]
timestamp = "#89ddff"
key = "#add7ff"
string = "#5de4c7"
number = "#fffac2"
bool = "#f087bd"
null = "#506477"
border_color = { fg = "#3b4261", bg = "#1b1e28" }
border_width = 1
border_padding = 1
