name = "rose-pine-dawn"

[colors]
background = "#faf4ed"
foreground = "#575279"
selection_bg = "#dfdad9"
selection_fg = "#575279"
overlay_bg = "#fffaf3"
status_bg = "#f4ede8"
status_fg = "#797593"
border = "#cecacd"
window_focus_border = "#ea9d34"
search_match = { fg = "#faf4ed", bg = "#ea9d34" }
dim = "#9893a5"

[levels]
trace = "#9893a5"
debug = "#56949f"
info = "#286983"
warn = "#ea9d34"
error = "#b4637a"
fatal = "#907aa9"
unknown = "#575279"

[ui]
timestamp = "#56949f"
key = "#d7827e"
string = "#286983"
number = "#ea9d34"
bool = "#907aa9"
null = "#9893a5"
border_color = { fg = "#cecacd", bg = "#faf4ed" }
border_width = 1
border_padding = 1
