name = "srcery"

[colors]
background = "#1c1b19"
foreground = "#fce8c3"
selection_bg = "#303030"
selection_fg = "#fce8c3"
overlay_bg = "#262626"
status_bg = "#121212"
status_fg = "#baa67f"
border = "#4e4e4e"
window_focus_border = "#fbb829"
search_match = { fg = "#1c1b19", bg = "#fbb829" }
dim = "#918175"

[levels]
trace = "#918175"
debug = "#2c78bf"
info = "#519f50"
warn = "#fbb829"
error = "#ef2f27"
fatal = "#e02c6d"
unknown = "#fce8c3"

[ui]
timestamp = "#2c78bf"
key = "#0aaeb3"
string = "#519f50"
number = "#ff5f00"
bool = "#e02c6d"
null = "#918175"
border_color = { fg = "#4e4e4e", bg = "#1c1b19" }
border_width = 1
border_padding = 1
