name = "vesper"

[colors]
background = "#101010"
foreground = "#ffffff"
selection_bg = "#232323"
selection_fg = "#ffffff"
overlay_bg = "#161616"
status_bg = "#161616"
status_fg = "#a0a0a0"
border = "#343434"
window_focus_border = "#ffc799"
search_match = { fg = "#101010", bg = "#ffc799" }
dim = "#8b8b8b"

[levels]
trace = "#8b8b8b"
debug = "#a0a0a0"
info = "#99ffe4"
warn = "#ffc799"
error = "#ff8080"
fatal = "#ffcfa8"
unknown = "#ffffff"

[ui]
timestamp = "#a0a0a0"
key = "#99ffe4"
string = "#99ffe4"
number = "#ffc799"
bool = "#ffcfa8"
null = "#8b8b8b"
border_color = { fg = "#343434", bg = "#101010" }
border_width = 1
border_padding = 1
